### ISSUE TITLE
Build error from git clone

### ISSUE THREAD

**Issue by grady** [richarddurbin/pbwt#38]
From a clone of the repository on github, running make gives:
```
$ make
cc -g -O3 -I../htslib  -c -o pbwtMain.o pbwtMain.c
pbwtMain.c: In function ‘pbwtCommitHash’:
pbwtMain.c:176:12: error: ‘PBWT_COMMIT_HASH’ undeclared (first use in this function)
     return PBWT_COMMIT_HASH ;
```
I needed to explicitly generate `version.h` before the build would proceed:
```
$ make version.h
# ...
$ make
# builds ok
```

**Comment by richarddurbin** [comment]
Sorry.  This is now fixed in the main github repository.  Richard

> On 11 Dec 2015, at 13:08, Grady Weyenberg <notifications@github.com> wrote:
> 
> From a clone of the repository on github, running make gives:
> 
> $ make
> cc -g -O3 -I/htslib  -c -o pbwtMaino pbwtMainc
> pbwtMainc: In function ‘pbwtCommitHash’:
> pbwtMainc:176:12: error: ‘PBWT_COMMIT_HASH’ undeclared (first use in this function)
>      return PBWT_COMMIT_HASH ;
> I needed to explicitly generate versionh before the build would proceed:
> 
> $ make versionh
> # 
> $ make
> # builds ok
> —
> Reply to this email directly or view it on GitHub <https://github.com/richarddurbin/pbwt/issues/38>.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
